services:
  payment-service:
    build: .
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "8086:8086"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@payment-db:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      payment-db:
        condition: service_healthy
    networks:
      - microservices-net

  payment-db:
    image: postgres:17-alpine
    container_name: payment-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5436:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  microservices-net:
    external: true
volumes:
  payment_data:
